test: &default

  # Credentials for REST APIs
  client_id: AYjZT2tas5_xjKODvKSW1DEXVieC0wn4EWR4H_bn7vfP4PwdjTlY5kjL640PZgRhrWbk71Fy62tO87IJ
  client_secret: EDuYKlUbkwgH8wGLetN0Gk6a0l4BUBuCFqh0JIvuXavIKBrewa5G5AAA7vbPpe_xd08GWfzSSvSuO9BX

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

development:
  <<: *default

production:
  <<: *default
  mode: live