test: &default

  # Credentials for REST APIs
  client_id: AcCp1ZKvcqBS3QxenYo8cI-PYrc2E8m07mIVqzTHj-yixNBkEK12LbSoptWDkKxPKb72-nkLCA93A7vD
  client_secret: ECnipckEVxtOwLlLzTdcvkfXA5zPF-wWIzJzlFXgZwNu6qIYtAJ2p2WtvL0e7U-76zFfPeBeJXbWIQOO

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: marvn.jimena-facilitator_api1.gmail.com
  password: QLV3K2XZLGWQP2H3
  signature: A9A0gZTWcGyirG.qnLuzNtP0Yj-IA5IeOJyTR7Ni6K.l.dBQqkq9Armq
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live